### ISSUE TITLE
What does "position" mean in Labels-v2.json and Labels-cameras.json files?

### ISSUE THREAD

**Issue by LittleFanFan** [SilvioGiancola/SoccerNetv2-DevKit#10]
Hi, I find "position" in annotations and assume it may relate to the frame index in the video. 
My question is, how can I use it to extract the exact frame index? Thanks

**Comment by cioppaanthony** [comment]
Hi, exactly. It corresponds to the time in millisecond of the action in the LQ videos.

Since the video is at 25fps, you can directly link it to the frame index of the video by: 
frame_index = int(position/40)

If you want to link it to the 2fps features:
frame_index = int(position/500)
