### ISSUE TITLE
Problem with the homography data in calibration json

### ISSUE THREAD

**Issue by PranshuAgrawal86** [SilvioGiancola/SoccerNetv2-DevKit#14]
I am working on the _1_field_calibration_ccbv.json_ to extract frames from the video using the corresponding _video.ini_ file under the assumption that a HQ video is 50 fps downsampled to 2 fps. 

Using the start time second present in .ini file & count of frames present, I am mapping the homography matrix to the corresponding frame. However, it seems to have homography data present for replay frames with high confidence score. 

Attached is an example, 
![8](https://user-images.githubusercontent.com/86658975/126954608-618473dc-f953-44ea-9f0a-b7aea98a611d.png)

is a frame present at 0:09:41 (calculated using the above assumption) has following data present in calibration.json

"homography": [
        3334.76123046875,
        -1385.3936767578125,
        -23787.22265625,
        -74.32776641845703,
        260.42376708984375,
        31227.6171875,
        -0.8536908626556396,
        -1.3100050687789917,
        85.80413818359375
      ],
      "conf": 0.931109577411863

and I am using the Task1-ActionSpotting/Calibration_GCN/src/dataset.py (https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/deda7eaae95de2637d43730a7708fc8199245ad9/Task1-ActionSpotting/Calibration_GCN/src/dataset.py) file 

& the following code to draw the calibration cone : 
`                # Visualization
                #for i, frame in enumerate(representation_half1):
                #    cv2.imwrite("outputs/test/"+str(i)+".png", frame)
                

                representation_half2 = np.zeros((feat_half2.shape[0], self.representation_height, self.representation_width, self.representation_channel), dtype=np.uint8)
                bbox_predictions = bbox_half2
                ratio_width = bbox_predictions["size"][2]/self.representation_width
                ratio_height = bbox_predictions["size"][1]/self.representation_height
                for i, bbox in enumerate(bbox_predictions["predictions"][0:feat_half2.shape[0]]):
                    if self.args.calibration:
                        confidence = calibration_half2["predictions"][i][0]["confidence"]
                        if confidence < self.calibration_threshold:
                            continue
                        homography = calibration_half2["predictions"][i][0]["homography"]
                        homography = np.reshape(homography, (3,3))
                        homography = homography/homography[2,2]
                        homography = np.linalg.inv(homography)
                        # Draw the field lines
                        if self.args.calibration_field:
                            representation_half2[i,int(0.025*self.representation_height): int(0.025*self.representation_height) + self.radar_image.shape[0], int(0.025*self.representation_width): int(0.025*self.representation_width) + self.radar_image.shape[1] ] =self.radar_image

                        # Draw the calibration cones
                        if self.args.calibration_cone:
                            frame_top_left_projected = unproject_image_point(homography, np.array([0,0,1]))
                            frame_top_right_projected = unproject_image_point(homography, np.array([calibration_half2["size"][2],0,1]))
                            frame_bottom_left_projected = unproject_image_point(homography, np.array([0,calibration_half2["size"][1],1]))
                            frame_bottom_right_projected = unproject_image_point(homography, np.array([calibration_half2["size"][2],calibration_half2["size"][1],1]))
                            frame_top_left_radar = meter2radar(frame_top_left_projected, self.dim_terrain, (self.representation_height, self.representation_width, self.representation_channel))
                            frame_top_right_radar = meter2radar(frame_top_right_projected, self.dim_terrain, (self.representation_height, self.representation_width, self.representation_channel))
                            frame_bottom_left_radar = meter2radar(frame_bottom_left_projected, self.dim_terrain, (self.representation_height, self.representation_width, self.representation_channel))
                            frame_bottom_right_radar = meter2radar(frame_bottom_right_projected, self.dim_terrain, (self.representation_height, self.representation_width, self.representation_channel))

                            pts = np.array([frame_top_left_radar[0:2], frame_top_right_radar[0:2], frame_bottom_right_radar[0:2], frame_bottom_left_radar[0:2]], np.int32)

                            representation_half2[i] = cv2.polylines(representation_half2[i], [pts], True, (255,255,255), 1)`

It seems that either the homography data present for this frame is incorrect or it's confidence value, or is there a problem with my mapping logic of homography data to the field_calibration_ccbv.json?

**Comment by cioppaanthony** [comment]
Hi @PranshuAgrawal86,

If the problem only occurs for some frames, but that most of them seem aligned with the calibration data, then it is that you probably have a correct alignment. This issue might simply come from the calibration predicting network (CCBV) that we used to generate these calibration data (just a reminder that the calibration data dos not correspond to manually annotated ground-truths! ). Of course, since the calibration network is not perfect it can make mistakes sometimes.

Otherwise, if you see a misalignment for most frames, then I would suggest you take a look at the function extracting the frames for the feature extraction (https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/0119a163a10d8cc7d3c1c5f76c5ef976542f11d8/Features/VideoFeatureExtractor.py#L74). If you use the FrameCV function from the devkit with a 25fps video, and setting the FPS parameter to 2, you should get the exact frames that you need.

Another option is to do it manually in a loop, still from a 25fps video. Check out this code:



```
import cv2
import numpy as np 
import json
import os
import sys

def unproject_image_point(homography, point2D):
	pitchpoint = homography @ point2D
	pitchpoint = pitchpoint/pitchpoint[2]
	return pitchpoint

def meter2radar(dim, point2D):
	return np.array([int(point2D[0] + dim[1]/2), int(point2D[1] + dim[0]/2), 1])
	

if __name__=="__main__":

	video_path = sys.argv[1]
	features_path = sys.argv[2]
	predictions_path = sys.argv[3]
	calibration_path = sys.argv[4]

	# Read the video
	video = cv2.VideoCapture(video_path)

	# Read the features
	features = np.load(features_path)
	print("Shape of the features:", features.shape)

	# Read the predictions
	file = open(predictions_path,'r')
	predictions = json.load(file)
	file.close()
	print("number of predictions: ", len(predictions["predictions"]))
	print("shape of the prediction video: ", predictions["size"])

	# Read the calibration
	file_c = open(calibration_path,'r')
	calibrations = json.load(file_c)
	file_c.close()
	print("number of calibrations: ", len(calibrations["predictions"]))
	print("shape of the calibration video: ", calibrations["size"])

	ret, frame = video.read()
	index = 0
	prediction_index = 0
	correct_indexes = np.ceil(np.arange(len(predictions["predictions"])+1)*12.5).astype(int)

	dim_terrain = (68,105,3)
	size_radar_point = 2

	while ret:
		
		index += 1

		if not index in correct_indexes:

			ret, frame = video.read()
			continue

		# Retrieve the correct prediction
		bboxes = predictions["predictions"][prediction_index]["bboxes"]
		colors = predictions["predictions"][prediction_index]["colors"]
		fields= predictions["predictions"][prediction_index]["onfield"]

		homography = calibrations["predictions"][prediction_index][0]["homography"]
		homography = np.reshape(homography, (3,3))
		homography = homography/homography[2,2]
		homography = np.linalg.inv(homography)
		confidence = calibrations["predictions"][prediction_index][0]["confidence"]

		original_width = predictions["size"][2]
		original_height = predictions["size"][1]
		new_width = frame.shape[1]
		new_height = frame.shape[0]

		radar = cv2.imread("outputs/radar.png")

		frame_top_left_projected = unproject_image_point(homography, np.array([0,0,1]))
		frame_top_right_projected = unproject_image_point(homography, np.array([original_width,0,1]))
		frame_bottom_left_projected = unproject_image_point(homography, np.array([0,original_height,1]))
		frame_bottom_right_projected = unproject_image_point(homography, np.array([original_width,original_height,1]))
		frame_top_left_radar = meter2radar(dim_terrain, frame_top_left_projected)
		frame_top_right_radar = meter2radar(dim_terrain, frame_top_right_projected)
		frame_bottom_left_radar = meter2radar(dim_terrain, frame_bottom_left_projected)
		frame_bottom_right_radar = meter2radar(dim_terrain, frame_bottom_right_projected)

		pts = np.array([frame_top_left_radar[0:2], frame_top_right_radar[0:2], frame_bottom_right_radar[0:2], frame_bottom_left_radar[0:2]], np.int32)

		radar = cv2.polylines(radar, [pts],True, (int(255*confidence), int(255*confidence), int(255*confidence)), 1)

		for box, color, field in zip(bboxes, colors, fields):

			if field == 0:
				continue

			x_top_left = int(box[0]*new_width/original_width)
			x_bottom_right = int(box[2]*new_width/original_width)
			y_top_left = int(box[1]*new_height/original_height)
			y_bottom_right = int(box[3]*new_height/original_height)

			projection_point = np.array([int((box[0]+box[2])/2), box[3], 1])
			projected_point = unproject_image_point(homography, projection_point)
			radar_point = meter2radar(dim_terrain, projected_point)

			frame = cv2.rectangle(frame, (x_top_left,y_top_left), (x_bottom_right,y_bottom_right), (color[0],color[1],color[2]),2)
			radar = cv2.rectangle(radar, (radar_point[0]-size_radar_point//2,radar_point[1]-size_radar_point//2), (radar_point[0]+size_radar_point//2,radar_point[1]+size_radar_point//2), (color[0],color[1],color[2]),-1)

		frame[0:radar.shape[0], frame.shape[1]//2-radar.shape[1]//2:frame.shape[1]//2+radar.shape[1]//2+1] = radar
		cv2.imwrite("check_imgs/"+str(prediction_index)+".png", frame)

		ret, frame = video.read()
		prediction_index +=1
```
![403_student](https://user-images.githubusercontent.com/31652699/126969630-c436cc89-7378-4a34-8dd9-9b2416e2d215.png)

More precisely, the correct indexes to take from the 25fps videos are given by: 
`correct_indexes = np.ceil(np.arange(len(predictions["predictions"])+1)*12.5).astype(int)` with the first frame of the 25fps video corresponding to the index 1, and not 0 (sorry about that, I know it's not practical) !!!
Also, len(predictions["predictions"]) should simply be the total number of frames at 2fps.

Hope this helps, don't hesitate to get back to me if you run into any issue.

**Comment by PranshuAgrawal86** [comment]
Hi @cioppaanthony , 
Thank you for sharing the response. 

We ran the script you posted on a low quality 25 fps video to visualize homography data using value of prediction_index = 0 and observed that homography looks misaligned with frames, in order to correct indexes, we noticed using minus -1 as prediction index results looks better with exception of first frame. 

(For your reference, attached here are the results & the corresponding calibration.json used to read homography). 
Video tested on : /england_epl/2016-2017/2016-08-14 - 18-00 Arsenal 3 - 4 Liverpool/1.mkv
Calibration.json used - /england_epl/2016-2017/2016-08-14 - 18-00 Arsenal 3 - 4 Liverpool/1_field_calibration_ccbv.json

[https://exrcsdrive.kaust.edu.sa/exrcsdrive/index.php/s/9eRjic29XTk0gS9/download?path=%2Fengland_epl%2F2016-2017%2F2016-08-14%20-%2018-00%20Arsenal%203%20-%204%20Liverpool&files=1_field_calibration_ccbv.json](url)

Result 1 : Visualization using prediction index = 0
![LQ_visualization_index0](https://user-images.githubusercontent.com/86658975/127286276-1e0438bc-47eb-4387-bc5c-54c604929cd0.png)

Result 2 : Visualization using prediction index = -1
![LQ_visualization_index_minus1](https://user-images.githubusercontent.com/86658975/127286403-e7b198a4-ae10-46b6-bf58-ac20dfe9f707.png)

Does these results seem to be accurate? or a misalignment still persists in these frames? 

Also, tried using FrameCV to extract frames which results in the same frames as this script.
Let us know your thoughts.

**Comment by cioppaanthony** [comment]
Hi @PranshuAgrawal86,

I'm sorry but it is a bit difficult to say for sure that they are perfectly aligned by looking at the frames you sent.
Anyway, FrameCV is the correct way to go to extract the frames from a 25fps video and you should not have a misalignment with this technique. It should also be aligned with the ResNET features provided that way.

To make sure that your alignment is correct, try looking at a lot of camera changes, if you see that a calibration from the previous camera is projected to the next one, then it means that there is a temporal misalignment. Of course, the predicting network can make mistakes, but it can be obvious that the radar printed corresponds to the previous camera, for instance if a lot of players are predicted on a close-up shot.

**Comment by SilvioGiancola** [comment]
Hi @PranshuAgrawal86 

I believe this issue is linked to https://github.com/SilvioGiancola/SoccerNetv2-DevKit/issues/16 .

Note that any field calibration method has his flaw, CCBV is no exception. You can imagine that when there is no line visible in the frame, the estimation can go terribly wrong. AFAIK, CCBV does no check for temporal consistency between frames. 

Feel free to check the code of CCBV from EVS Broadcast for further analysis: https://github.com/evs-broadcast/CCBV .

Cheers
