### ISSUE TITLE
annotation tool error

### ISSUE THREAD

**Issue by jihwanp** [SilvioGiancola/SoccerNetv2-DevKit#15]
Hi thanks for providing great work!
I currently do project related to soccer, and I want to annotate myself for my own task.
I tried to use annotation tool but I got error when running python main.py in annotetion/src.

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from interface.main_window import MainWindow
  File "/home/jihwan/SoccerNetv2-DevKit/Annotation/replays/src/interface/main_window.py", line 4, in <module>
    from PyQt5.QtMultimedia import QMediaPlayer
ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`

What should I do for this?

**Comment by cioppaanthony** [comment]
Hi @jihwanp. 

Thanks for your interest! On which OS are you running the code? We developed the annotation tool for linux  (Ubuntu) and managed to make it work with a few adjustments for Windows. Unfortunately, we were unable to make it work on Mac OS. Could that be related to your issue?

I wish you the best for your project, don't hesitate to get back to me if that wasn't the issue and we'll figure it out.

**Comment by SilvioGiancola** [comment]
Hi @jihwanp, have you solved your issue? I believe you are simply missing a library in you linux-based OS, in particular `libpulse-mainloop-glib.so.0`. If you are on Ubuntu, you could simply run `sudo apt-get install -y libpulse-mainloop-glib0`. Let us know if you are still facing any issue. Best
