### ISSUE TITLE
CNN architecture 

### ISSUE THREAD

**Issue by Al-Hussein-96** [SilvioGiancola/SoccerNetv2-DevKit#17]
can you explain me the Neural Network architecture  (CNN) in SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/model.py  ?

the number of layers and ...........

**Comment by cioppaanthony** [comment]
Hi @Al-Hussein-96,

Please find here a detailed diagram of the layers: [CALFNet.pdf](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/files/7012358/CALFNet.pdf)

If you need more details in a text form, you can also refer to the Appendix A.2 in my PhD Thesis: [Thesis.pdf](https://orbi.uliege.be/bitstream/2268/252147/1/Cioppa2020RealTimeSemantics_PhD-thesis.pdf) starting at page 153 with the same diagram at page 158.

I hope this helps don't hesitate to get back if you have more questions.

**Comment by Al-Hussein-96** [comment]
@cioppaanthony 

thank you bro

**Comment by cioppaanthony** [comment]
You're welcome!
