### ISSUE TITLE
About Task1-ActionSpotting‘s results

### ISSUE THREAD

**Issue by Pandasea** [SilvioGiancola/SoccerNetv2-DevKit#2]
I see the result in the task1'code:
Example: NetVLAD on SoccerNet v2 (17 classes - Average-mAP=31.37%))，whick is consistent with the result of my experiment.
But in the paper, from table 2, the result is 39.7. I want to know what optimizations have caused the improvement of results. Thanks a lot.

**Comment by SilvioGiancola** [comment]
Dear @Pandasea, 

Please consider the reproducible results of NetVLAD reported in this repository and on the evaluation server. The arxiv paper is only a pre-print, and contains a flaw in the exact row of the table you mentioned. We will be update the paper soon.

If you are looking for competitive results, you can always adjust the NMS threshold as referred in [Task1-ActionSpotting/Pooling](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/Pooling#note-on-performances). We refrained in doing so in the paper and prefered reproducing the baselines as designed in their original papers.

Best,
