### ISSUE TITLE
[Annotation Tool Error] "main.py", ModuleNotFoundError: No module named 'interface'

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#21]
Hi Silvio Giancola & SoccerNetv2-DevKit team, this is a great repo you have put together here, thank you so much for making it public!

I came across this [SoccerNet-v2 challenge - Tutorial #2 (live session)](https://www.youtube.com/watch?v=U-fhb1RnRzM&list=PLW--L_tD2yC87yCMVkIwSRUxsGwcCkpsZ&index=2&t=193s) video from your YouTube channel. 
I'm following along in "02:18​ Demo 1: Annotation and visualization tool", and upon running `main.py`, I've come across an error: 
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from interface.main_window import MainWindow
ModuleNotFoundError: No module named 'interface'
```

My Steps: 
1. `git clone`-ed the repo
2. Created environment based on 4 lines in Annotation's "Getting Started"
3. Ran ./Annotation/actions/src/main.py

If there's anyone that could let me know if this is an error on my end, or how to fix this, I'd be greatly appreciated! 

(Note: Regarding the issue I opened a few minutes ago, it was a miss-click but I can't delete it - apologies for the inconvenience)

**Comment by Wilann** [comment]
Update: 
I'm running Pop!_OS 20.04 LTS - a distro of Ubuntu. 
I came across Issue #15 and tried running `sudo apt-get install -y libpulse-mainloop-glib0` but the error still persists.

**Comment by cioppaanthony** [comment]
Hi @Wilann,

Many thanks, we're glad that you're enjoying working on this topic! :-)

Regarding the error, the most probable mistake is that you are launching the code from the wrong folder. 

You should run it like this:

``` 
cd Annotation/actions/src/
python3 main.py
```

Also, make sure that the dynamic link inside of src is correctly linked to the interface folder (to Annotation/actions/interface/)

Keep me posted if this solved your issue!

**Comment by Wilann** [comment]
Hey @cioppaanthony, 

Thank you so much for your reply! 

I've tried running it the way you suggested, and am still getting the error. 

Regarding the dynamic link in `./Annotation/actions/interface/src/`, I wasn't aware that I needed to link it to `./Annotation/actions/interface/`
I'm not sure what a dynamic link is in this context. Are you referring to the `interface` text file, which contains:
```
XSym
0013
52e1e617b9e9de819c4ef408677ba21d
../interface/
```
If so, how would I link these two things?

**Comment by SilvioGiancola** [comment]
Hi @Wilann, it should be linked automatically, but maybe your custom linux OS does not support it. Anyway, your issue is very simple, your `main.py` can't see the module (=folder) `interface` from where you launch it. You can link it with something like `ln -s <FROM> <TO>` or simply copy-paste the folder `interface` where you code requires it. Hope that helps! Cheers

**Comment by Wilann** [comment]
Hi @SilvioGiancola, sorry for the late reply. 
I couldn't get the link to work - I got this message when in `/actions/src` and running `ln -s main.py interface`:
`ln: failed to create symbolic link 'interface': File exists`

I decided to move `main.py` into `/actions` from `/actions/src`. It seems to work, but I appear to be missing some kind of config file. Running `python main.py` now gives me this error:
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    window = MainWindow()
  File "/media/wilsonchan/Giratina/Projects/Badi Start-Up (v2 Badi Highlights)/SoccerNetv2-DevKit (git clone)/Annotation/actions/interface/main_window.py", line 37, in __init__
    self.init_main_window()
  File "/media/wilsonchan/Giratina/Projects/Badi Start-Up (v2 Badi Highlights)/SoccerNetv2-DevKit (git clone)/Annotation/actions/interface/main_window.py", line 50, in init_main_window
    self.event_window = EventSelectionWindow(self)
  File "/media/wilsonchan/Giratina/Projects/Badi Start-Up (v2 Badi Highlights)/SoccerNetv2-DevKit (git clone)/Annotation/actions/interface/event_selection.py", line 23, in __init__
    self.init_window()
  File "/media/wilsonchan/Giratina/Projects/Badi Start-Up (v2 Badi Highlights)/SoccerNetv2-DevKit (git clone)/Annotation/actions/interface/event_selection.py", line 29, in init_window
    with open('../config/classes.txt') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../config/classes.txt'
```

**Comment by Wilann** [comment]
Update: Ah, I see that to change the labels I have to update the 3 files in `/config`. 
I'm still not sure why `../config/classes.txt` can't be opened from `/actions`

**Comment by Wilann** [comment]
Update 2: Ah, I see I just needed to remove the `..` since the directory is with respect to my Terminal, not the file location. Sorry - beginners mistake!
