### ISSUE TITLE
Task1 CALF Training - PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#24]
Hi @SilvioGiancola, 

I'm trying to run the CALF code for Task 1 with around 400 GB of the entire dataset so far (download is taking a while, so I wanted to try training with the data I have for now).

When in, `/Task1-ActionSpotting/CALF`, running, 
```
python src/main.py --SoccerNet_path="/../../Download/Videos" \
--features=ResNET_TF2_PCA512.npy \
--num_features=512 \
--model_name=CALF_v2 \
--batch_size 32 \
--evaluation_frequency 20 \
--chunks_per_epoch 18000 \
```
I get error `PermissionError: [Errno 13] Permission denied: '/../../Download'`

`Download/Videos` is where I downloaded the SoccerNet dataset. It has folders like "england_epl", "europe_uefa-champions-league", etc. 
And, in `DownloadSoccerNet.py`, I referred to this folder as the directory to download to: `mySoccerNetDownloader = SoccerNetDownloader(LocalDirectory="./Videos")`

Do you have any idea what the issue is? 

Thank you so much for your time! Looking forward to your response.

**Comment by SilvioGiancola** [comment]
Try changing "/../../Download/Videos" into "../../Download/Videos" or "./../../Download/Videos". "/../../Download/Videos" cannot exist, it's beyond your root folder.

**Comment by Wilann** [comment]
It worked - thank you so much! Apologies for the beginner mistakes.
