### ISSUE TITLE
Custom Feature Extractor - Features/VideoFeatureExtractor.py: TensorFlow vs PyTorch, Output Dimension, Extraction Speed

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#27]
Hi SoccerNet Dev Team, 

I have a question regarding the technical (?) aspect of `Features/VideoFeatureExtractor.py` 

I see that you were considering using PyTorch for the backend, but ultimately decided to go with TensorFlow. Is there a reason for this? 

Also, when extracting the frames of the video, I see that you're using `SoccerNet.DataLoader.Frame` and `SoccerNet.DataLoader.FrameCV` (depending on OpenCV/SKVideo backend) at 2 FPS, then preprocessing with `tensorflow.keras.applications.resnet.preprocess_input`.
After running a custom video through this pipeline, I end up with `frames.shape = num_frames=(8393, 224, 224, 3)`. What confuses me even more is that when loading the  `ResNET_TF2.npy` file, the shape seems to be `(8393, 2048)` 
Could you please explain what these dimensions represent? I believe 3 are the color channels, and 2048 are the number of ResNet features, but I'm unsure of where 8393 and 224 come from. 

About optimization, during the extraction, it seems that my CPU is only using ~15% of its maximum speed. Is there a way to optimize this in the backend (`SoccerNet.DataLoader.Frame` and `SoccerNet.DataLoader.FrameCV` I assume)

Thank you for your time again, and hoping you can help me in understanding your code a little better!

**Comment by GriesserP** [comment]
Hello (I am not from the SoccerNet Team) but I can give you an answer about the shapes of the tensor.
Here the resnet model takes Nx224x224x3 images as input and outputs Nx2048 i.e. one vector of dimension 2048 per image (or frame) so 224x224 is the width and height of the frames and 8393 is the number of frame extracted at 2fps. So you video lasts around 8393/2 seconds i.e. 70minutes. Hope it helps

**Comment by Wilann** [comment]
Hello @GriesserP, thank you so much for the explanation (it makes perfect sense)! As I understand it now, this is just how the ResNet model works, and isn't necessarily due to the SoccerNet dataset.

**Comment by Wilann** [comment]
Regarding an update for feature loading speed, I have discovered about Nvidia's DALI, and will attempt to update the code with it.
