### ISSUE TITLE
Models CALF_calibration approach

### ISSUE THREAD

**Issue by antosanto97** [SilvioGiancola/SoccerNetv2-DevKit#29]
Hi guys, first of all thank you for share all this knowledge, it is impressive. I was wondering if it can be possible to access the models of CALF_calibration approach since training for scratch the networks in my case is very slow. I am doing my master thesis and I am trying to reproduce the experimentation that you did, this is the reason which I am interested in that.

Sorry for inconvenience and thank you very much.

**Comment by SilvioGiancola** [comment]
Hi @antosanto97 , thank you for raising this issue. We will upload the models of CALF_calibration within this folder: https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF_Calibration/models with the precious help of @cioppaanthony :) Stay tuned.

**Comment by cioppaanthony** [comment]
Hi @antosanto97!

Thanks for your comment. :+1: 

As requested, I have uploaded our two [models](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF_Calibration/models):
1. Trained on the 8 visual classes with the help of calibration,
2. and trained on the 9 other non-visual classes without calibration information.

I also invite you to check out the new version of the [README](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF_Calibration/) where I added a section related to "how to use these pre-trained weights for inference on SoccerNet". The command lines to run these models can be found there as well.

Don't hesitate to give me your feedback on the matter! I would be glad to help you should you have any issue or question.

I wish you all the best in your work.
