### ISSUE TITLE
how to run model CALF_Calibration_GCN on external video to get actions?

### ISSUE THREAD

**Issue by DogFortune** [SilvioGiancola/SoccerNetv2-DevKit#34]
https://github.com/SilvioGiancola/SoccerNetv2-DevKit/issues/5

I'm using model CALF_Calibration_GCN. 
I want to use U to get the action of an external video.

**Comment by cioppaanthony** [comment]
Hi @DogFortune,

You can start by running the calibration algorithm (CCBV: https://github.com/evs-broadcast/CCBV/tree/main/calibration_data) on your video as well as Mask R-CNN to get the calibration and player data in a similar form than what we provide in SoccerNet (be aware that CCB is trained only for soccer videos). 

Then, you can run our trained CALF model on that video similar to what is done here: (https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF/inference)


I'm sorry we could not provide a complete pipeline like for CALF as the code comes from different sources (EVS company and us).

Anyway, I would suggest you start by trying our CALF pipeline for external video first, before trying to include the calibration in the mix! :-)

**Comment by DogFortune** [comment]
@cioppaanthony 

OK!! Thank you!!

**Comment by DogFortune** [comment]
@cioppaanthony 

Sorry, I have another question.

Do you need ResNET features for CALF_Calibration_GCN?
https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Features

**Comment by cioppaanthony** [comment]
@DogFortune,

If you use the argument --backbone_features=2DConv, you will need the ResNET features. This is by default in our code. 

Please note that even if you don't want to use these features at all, the code still relies on them being available for the dataset preloading, even if they might be unused by the model later on. This particular code is actually more of a "research code" than a "final-product code". It is shared in order for anyone to check the results of the paper, but not really to be directly integrated in a product.

**Comment by DogFortune** [comment]
@cioppaanthony 
Thank you for answering my question!
I'm sorry if my English is unfamiliar and the text is wrong.

**Comment by cioppaanthony** [comment]
@DogFortune

No worries about your English level, I was able to fully understand what you meant. :-) 
Good luck in your future research!
