### ISSUE TITLE
For Inference on an external Soccer Video File, do I still need camera calibration for action spotting ?

### ISSUE THREAD

**Issue by ghost** [SilvioGiancola/SoccerNetv2-DevKit#36]
I'm in assumption that only Calf, Calf GCN needs Camera calibration , does Netvlad++ needs camera calibration?

**Comment by ghost** [comment]
Also can I run this on frame by frame based scenarios? so to get exact timestamps

**Comment by Wilann** [comment]
Hi @ShanuD11, I'm not part of the SoccerNet team, but in my understanding all 3 methods need frame features, but CALF CGN also needs the camera calibrations

**Comment by ghost** [comment]
So netvlad++ is totally based out of spatio temporal features, am I right?

**Comment by Wilann** [comment]
As I understand it, yes (although you need annotations as well of course)

**Comment by SilvioGiancola** [comment]
Hi @ShanuD11 ,

Only CALF_Calibration and CALF_Calibration_GCN require field calibration files. CALF, Pooling and TemporallyAwarePooling do not require field calibration files.

All those baselines are based on frame features extracted from videos. Most of them are spatio temporal features (i.e. they have a temporal receptive field and require a stack of frames), except ResNET that is spatial only, hence could be a fit for your scenario based on frames only. 

Note that you will have to adapt the dataloader to load your frames, extract your features, then plug any spotting method, whether it is CALF or NetVLAD++. We do provide code for all those module, but you'll have to stack them in a single dataloader.
