### ISSUE TITLE
Starting from scratch

### ISSUE THREAD

**Issue by Tortoise17** [SilvioGiancola/SoccerNetv2-DevKit#37]
I would like to know that using this kit, from where to start?
Can I use the already trained model for the fine tuning? or I have to train from scratch using your features?

**Comment by cioppaanthony** [comment]
Hi @Tortoise17, 

Note that this repository will soon be deprecated and replaced by these one: https://github.com/SoccerNet/sn-spotting and https://github.com/SoccerNet/sn-grounding.

For starters, I would suggest you check out the Action Spotting Task and the CALF or NetVLAD methods that are in the related folder.

For CALF, you can use the pre-trained model for fine-tuning, you should be able to do so by simply adding the <code> --load_weight models/CALF_benchmark/model.pth.tar </code> argument to the command lines. This will start the training from the pre-trained model.

I hope this helps.

**Comment by Tortoise17** [comment]
Thank you so much. The pre-trained model is open-source free to be used ? or under some specific license?

**Comment by cioppaanthony** [comment]
Yes, it is shared under an Apache v2 License (https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/main/Task1-ActionSpotting/CALF/LICENSE), which is quite permissive. 

If you could just cite our paper or repository when you use it that would be great, thanks.

**Comment by Tortoise17** [comment]
Of course, I would definitely acknowledge specially thank in special part of paper and citing is for sure must.

**Comment by cioppaanthony** [comment]
That's great, thanks! Good luck on your future work.

**Comment by skfaysal** [comment]
Hi @cioppaanthony 
How can i fine tune the "model.pth.tar" model for a dataset that has different output class?
lets say the pretrained model("model.pth.tar") has 17 output class but i want to fine-tune it for a dataset which has 4 class.
