### ISSUE TITLE
How to download the 25fps features for challenge?

### ISSUE THREAD

**Issue by shenyuanyuan** [SilvioGiancola/SoccerNetv2-DevKit#4]
I have download the 25fps for train, valid, and test. However, when I try it for challenge, it's failed. I want to know how can I download the 25fps features for challenge?

**Comment by SilvioGiancola** [comment]
Sorry, we have not extracted the 25fps features for the challenge, only the 2fps.
Have a look at our [feature extraction code](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Features) to extract your own version of the features. In particular, have a look at [this script](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/main/Features/ExtractResNET_TF2.py#L193) and set the parameter `--FPS=25.0`.

I hope that will help.

**Comment by shenyuanyuan** [comment]
okay, I will try, thanks for your reply.
