### ISSUE TITLE
Replay grounding json

### ISSUE THREAD

**Issue by Tortoise17** [SilvioGiancola/SoccerNetv2-DevKit#42]
@SilvioGiancola I have to ask that how can we get the human readable json from Task3 replay grounding for external video? is there any hint or possible advise which I can follow would be great help from you.

**Comment by SilvioGiancola** [comment]
Hi @Tortoise17 , I am not sure we provide the code for inference of a single external video. I guess one can easily adapt the train+test code provided in the repo, and adapt it to infer on a single game.

**Comment by Tortoise17** [comment]
@SilvioGiancola thank you. One more question. For the Task2 camera calibration, we have to input `homography` as field calibration which can be computed from CCBV? or can also be computed from this dev-kit? and in result we get the camera-calibration.json? Is there any sequence available in the same kit for getting this as output?

**Comment by SilvioGiancola** [comment]
AFAIK, this is the code for CCBV: https://github.com/evs-broadcast/CCBV
I would recommend you to ask your question on https://github.com/SoccerNet/sn-calibration :)
