### ISSUE TITLE
NAN with TemporallyAwarePooling

### ISSUE THREAD

**Issue by ajtao** [SilvioGiancola/SoccerNetv2-DevKit#44]
Running into NaN loss after 220 epochs with NetVLAD++ in the TemporallyAwarePooling context. Any suggestions? Different LR haven't fixed. I think it might be coming from the weighted NLLLoss, but i'm not sure yet.

**Comment by SilvioGiancola** [comment]
What data are you using? If you change the data you might have to change the hyperparameters, starting from the LR and different batch size.
