### ISSUE TITLE
Is the NDA access to vedio still available?

### ISSUE THREAD

**Issue by xuyifan-0731** [SilvioGiancola/SoccerNetv2-DevKit#49]
Hi, i tried to use https://[soccer-net.org](https://soccer-net.org/)/ to get the password to download the vedio, but i found that a ERR_CONNECTION_REFUSED was announced by it. Could I use this website to fetch the password of vedio, or is there any other ways to get the vedio?

**Comment by SilvioGiancola** [comment]
Hi, where have found this link https://soccer-net.org/? The link is now https://www.soccer-net.org/ . All the information are there.

**Comment by xuyifan-0731** [comment]
thanks a lot. it solved my problem.
