### ISSUE TITLE
how to run model CALF on external video to get actions?

### ISSUE THREAD

**Issue by Al-Hussein-96** [SilvioGiancola/SoccerNetv2-DevKit#5]

**Comment by cioppaanthony** [comment]
Hi @Al-Hussein-96,

There is no direct function provided to do this, but you can easily adapt the code to your needs. Here is how to proceed.

1. Start by extracting the features of your video using the following command line: 
<code>python Features/VideoFeatureExtractor.py --path_video <PATH_INPUT_VIDEO> --path_features <PATH_OUTPUT_FEATURES> [--start <START_TIME_SECOND> --duration <DURATION_SECOND> --overwrite --PCA "Features/pca_512_TF2.pkl" --PCA_scaler "Features/average_512_TF2.pkl"]</code>
Store them in a folder with the name of the game for instance.

2. Replace in src/dataset.py at line 163:
<code>self.listGames = getListGames(split) ->self.listGames = [your_video_path] #in a list, you can put many there </code>

3. Replace in the get item that follows at line 188 and 189: 
<code>feat_half1 = np.load(os.path.join(self.path, self.listGames[index], "1_" + self.features)) -> feat_half1 = np.load(os.path.join(self.listGames[index], "1_" + self.features))</code>
You can also remove everything from line 196 to 226 if you don't have the labels.

3. Collect your results right at line 264 in src/train.py. If you do not have labels, remove also the computation of the metric from line 267 to 277.

4. Run the code in test mode, so with the <code>--test_only</code> argument and providing the correct name for the model to fetch (CALF_benchmark for instance)

I hope this helps, don't hesitate ask if you encounter an issue with this procedure.

**Comment by yurii-pryimak** [comment]
VideoFeatureSExtractor.py -> VideoFeatureExtractor.py

**Comment by cioppaanthony** [comment]
Thanks @yurii-pryimak! I corrected the Readme and my above comment.

**Comment by yurii-pryimak** [comment]
Hello, could you pls provide more details:
I have created folder with soccer game video next to SoccerNetv2-DevKit structure like below:

|-SoccerNetv2-DevKit
|-bd4
    |----bd4.mp4

1. Run below code :
`!python ./Features/VideoFeatureExtractor.py --path_video ../bd4/bd4.mp4 --path_features ../bd4/bd4_out_features.npy --overwrite --PCA "Features/pca_512_TF2.pkl" --PCA_scaler "Features/average_512_TF2.pkl"`

and got bd4_out_features.npy file inside bd4 folder.

2. update  src/dataset.py at line 163: like
`        self.listGames = ['../../bd4/bd4.mp4']`


3. Replace in the get item that follows at line 188 and 189: like
```
        feat_half1 = np.load(os.path.join(self.listGames[index], "1_" + self.features))
        feat_half2 = np.load(os.path.join(self.listGames[index], "2_" + self.features))
```
and removed lines 196 to 226

4. Collect your results right at line 264 in src/train.py. If you do not have labels, remove also the computation of the metric from line 267 to 277.

How I should I collect the result in 264 row?

5. Run the code in test mode, so with the --test_only argument and providing the correct name for the model to fetch (CALF_benchmark for instance)

should I download SoccerNet first?

`mySoccerNetDownloader = SoccerNetDownloader(LocalDirectory="/path/to/SoccerNet")`

is below code is correct to run the CALF_benchmark model in test mode?
```
!python src/main.py --SoccerNet_path=/path/to/SoccerNet/ \
--features=../../bd4/bd4_out_features.npy \
--num_features=512 \
--model_name=CALF_benchmark \
--test_only
```

Thanks!

**Comment by cioppaanthony** [comment]
Since you are not the first person to ask for this feature, I will add it to my tasks and try to implement a complete pipeline after the CVPR conference and push it to this github.

In the meantime, here is a possible workaround for your specific case:

The code right now expects two half times of the game, in something like "1_ResNET_TF2_PCA512.npy" and "2_ResNET_TF2_PCA512.npy". As a simple workaround, you can rename you feature <code>1_bd4_out_features.npy</code> and make a copy named <code>2_bd4_out_features.npy</code> and use <code>--features=bd4_out_features.npy </code> as argument. Place these two files inside your bd4 folder.

Update src/dataset.py at line 163: like
<code<self.listGames = ['bd4/']</code>

DON'T replace line 188 and 189 (sorry the previous comment might have been misleading for your specific case), so keep:
<code>
feat_half1 = np.load(os.path.join(self.path, self.listGames[index], "1_" + self.features))        
feat_half2 = np.load(os.path.join(self.path, self.listGames[index], "2_" + self.features))
</code>

The results will be saved in the outputs folder in json format automatically by line 264 of train.py.

and your full arguments should be:
<code>
!python src/main.py --SoccerNet_path=../../ \
--features=bd4_out_features.npy \
--num_features=512 \
--model_name=CALF_benchmark \
--test_only
</code>

PS: You don't need to download the soccernet dataset if you remove lines 176 to 181.

I really hope this helps. Tell me if this works for you! Otherwise, send me your issues and error messages and we can work it out together.

Otherwise, if you are not in a rush, I will try to implement the full pipeline by mid-july. 

Best,

**Comment by yurii-pryimak** [comment]
@cioppaanthony Thank you for your reply.

So for execution code
```
!python src/main.py --SoccerNet_path=../../../ \
--features=bd4_out_features.npy \
--num_features=512 \
--model_name=CALF_benchmark \
--test_only
```

I got below error log:
```
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]  Starting main function
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]  Parameters:
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]   SoccerNet_path : ../../../
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]         features : bd4_out_features.npy
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]       max_epochs : 1000
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]     load_weights : None
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]       model_name : CALF_benchmark
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]        test_only : True
2021-06-16 20:58:01,143 [MainThread  ] [INFO ]        challenge : False
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]         K_params : None
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]     num_features : 512
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]  chunks_per_epoch : 18000
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]  evaluation_frequency : 20
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]      dim_capsule : 16
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]        framerate : 2
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]       chunk_size : 120
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]  receptive_field : 40
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]     lambda_coord : 5.0
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]     lambda_noobj : 0.5
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]  loss_weight_segmentation : 0.000367
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]  loss_weight_detection : 1.0
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]       batch_size : 32
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]               LR : 0.001
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]         patience : 25
2021-06-16 20:58:01,144 [MainThread  ] [INFO ]              GPU : -1
2021-06-16 20:58:01,145 [MainThread  ] [INFO ]   max_num_worker : 4
2021-06-16 20:58:01,145 [MainThread  ] [INFO ]         loglevel : INFO
2021-06-16 20:58:01,153 [MainThread  ] [INFO ]  ContextAwareModel(
  (conv_1): Conv2d(1, 128, kernel_size=(1, 512), stride=(1, 1))
  (conv_2): Conv2d(128, 32, kernel_size=(1, 1), stride=(1, 1))
  (pad_p_1): ZeroPad2d(padding=(0, 0, 5, 6), value=0.0)
  (pad_p_2): ZeroPad2d(padding=(0, 0, 13, 13), value=0.0)
  (pad_p_3): ZeroPad2d(padding=(0, 0, 19, 20), value=0.0)
  (pad_p_4): ZeroPad2d(padding=(0, 0, 39, 40), value=0.0)
  (conv_p_1): Conv2d(32, 8, kernel_size=(12, 1), stride=(1, 1))
  (conv_p_2): Conv2d(32, 16, kernel_size=(27, 1), stride=(1, 1))
  (conv_p_3): Conv2d(32, 32, kernel_size=(40, 1), stride=(1, 1))
  (conv_p_4): Conv2d(32, 64, kernel_size=(80, 1), stride=(1, 1))
  (pad_seg): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_seg): Conv2d(152, 272, kernel_size=(3, 1), stride=(1, 1))
  (batch_seg): BatchNorm2d(240, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
  (max_pool_spot): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (pad_spot_1): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_spot_1): Conv2d(289, 32, kernel_size=(3, 1), stride=(1, 1))
  (max_pool_spot_1): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (pad_spot_2): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_spot_2): Conv2d(32, 16, kernel_size=(3, 1), stride=(1, 1))
  (max_pool_spot_2): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (conv_conf): Conv2d(464, 30, kernel_size=(1, 1), stride=(1, 1))
  (conv_class): Conv2d(464, 255, kernel_size=(1, 1), stride=(1, 1))
  (softmax): Softmax(dim=-1)
)
2021-06-16 20:58:01,153 [MainThread  ] [INFO ]  Total number of parameters: 578245
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 164, in <module>
    main(args)
  File "src/main.py", line 83, in main
    a_mAP, a_mAP_per_class, a_mAP_visible, a_mAP_per_class_visible, a_mAP_unshown, a_mAP_per_class_unshown = test(test_loader, model=model, model_name=args.model_name, save_predictions=True)
  File "/content/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/train.py", line 206, in test
    for i, (feat_half1, feat_half2, label_half1, label_half2) in t:
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/dataset.py", line 243, in __getitem__
    clip_length=self.chunk_size)
  File "/content/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/dataset.py", line 238, in feats2clip
    return feats[idx,:]
IndexError: index -220 is out of bounds for dimension 0 with size 20
```

**Comment by yurii-pryimak** [comment]
After adjusting chunk_size=240, receptive_field=80 I got:
`!python src/main.py --SoccerNet_path=../../../ \
--features=bd4_out_features.npy \
--num_features=512 \
--model_name=CALF_benchmark \
--test_only \
--chunk_size 240 \
--receptive_field 80`

```
> `2021-06-16 21:02:46,701 [MainThread  ] [INFO ]  Starting main function
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]  Parameters:
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]   SoccerNet_path : ../../../
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]         features : bd4_out_features.npy
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]       max_epochs : 1000
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]     load_weights : None
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]       model_name : CALF_benchmark
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]        test_only : True
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]        challenge : False
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]         K_params : None
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]     num_features : 512
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]  chunks_per_epoch : 18000
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]  evaluation_frequency : 20
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]      dim_capsule : 16
> 2021-06-16 21:02:46,702 [MainThread  ] [INFO ]        framerate : 2
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]       chunk_size : 240
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]  receptive_field : 80
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]     lambda_coord : 5.0
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]     lambda_noobj : 0.5
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]  loss_weight_segmentation : 0.000367
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]  loss_weight_detection : 1.0
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]       batch_size : 32
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]               LR : 0.001
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]         patience : 25
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]              GPU : -1
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]   max_num_worker : 4
> 2021-06-16 21:02:46,703 [MainThread  ] [INFO ]         loglevel : INFO
> 2021-06-16 21:02:46,714 [MainThread  ] [INFO ]  ContextAwareModel(
>   (conv_1): Conv2d(1, 128, kernel_size=(1, 512), stride=(1, 1))
>   (conv_2): Conv2d(128, 32, kernel_size=(1, 1), stride=(1, 1))
>   (pad_p_1): ZeroPad2d(padding=(0, 0, 11, 11), value=0.0)
>   (pad_p_2): ZeroPad2d(padding=(0, 0, 26, 27), value=0.0)
>   (pad_p_3): ZeroPad2d(padding=(0, 0, 39, 40), value=0.0)
>   (pad_p_4): ZeroPad2d(padding=(0, 0, 79, 80), value=0.0)
>   (conv_p_1): Conv2d(32, 8, kernel_size=(23, 1), stride=(1, 1))
>   (conv_p_2): Conv2d(32, 16, kernel_size=(54, 1), stride=(1, 1))
>   (conv_p_3): Conv2d(32, 32, kernel_size=(80, 1), stride=(1, 1))
>   (conv_p_4): Conv2d(32, 64, kernel_size=(160, 1), stride=(1, 1))
>   (pad_seg): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
>   (conv_seg): Conv2d(152, 272, kernel_size=(3, 1), stride=(1, 1))
>   (batch_seg): BatchNorm2d(480, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
>   (max_pool_spot): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
>   (pad_spot_1): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
>   (conv_spot_1): Conv2d(289, 32, kernel_size=(3, 1), stride=(1, 1))
>   (max_pool_spot_1): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
>   (pad_spot_2): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
>   (conv_spot_2): Conv2d(32, 16, kernel_size=(3, 1), stride=(1, 1))
>   (max_pool_spot_2): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
>   (conv_conf): Conv2d(944, 30, kernel_size=(1, 1), stride=(1, 1))
>   (conv_class): Conv2d(944, 255, kernel_size=(1, 1), stride=(1, 1))
>   (softmax): Softmax(dim=-1)
> )
> 2021-06-16 21:02:46,715 [MainThread  ] [INFO ]  Total number of parameters: 936965
> Traceback (most recent call last):
>   File "src/main.py", line 164, in <module>
>     main(args)
>   File "src/main.py", line 81, in main
>     model.load_state_dict(checkpoint['state_dict'])
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for ContextAwareModel:
> 	size mismatch for conv_p_1.weight: copying a param with shape torch.Size([8, 32, 12, 1]) from checkpoint, the shape in current model is torch.Size([8, 32, 23, 1]).
> 	size mismatch for conv_p_2.weight: copying a param with shape torch.Size([16, 32, 27, 1]) from checkpoint, the shape in current model is torch.Size([16, 32, 54, 1]).
> 	size mismatch for conv_p_3.weight: copying a param with shape torch.Size([32, 32, 40, 1]) from checkpoint, the shape in current model is torch.Size([32, 32, 80, 1]).
> 	size mismatch for conv_p_4.weight: copying a param with shape torch.Size([64, 32, 80, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 160, 1]).
> 	size mismatch for batch_seg.weight: copying a param with shape torch.Size([240]) from checkpoint, the shape in current model is torch.Size([480]).
> 	size mismatch for batch_seg.bias: copying a param with shape torch.Size([240]) from checkpoint, the shape in current model is torch.Size([480]).
> 	size mismatch for batch_seg.running_mean: copying a param with shape torch.Size([240]) from checkpoint, the shape in current model is torch.Size([480]).
> 	size mismatch for batch_seg.running_var: copying a param with shape torch.Size([240]) from checkpoint, the shape in current model is torch.Size([480]).
> 	size mismatch for conv_conf.weight: copying a param with shape torch.Size([30, 464, 1, 1]) from checkpoint, the shape in current model is torch.Size([30, 944, 1, 1]).
> 	size mismatch for conv_class.weight: copying a param with shape torch.Size([255, 464, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 944, 1, 1]).`
```

**Comment by cioppaanthony** [comment]
On the one hand, for your second error, that is perfectly normal, the network architecture depends on the receptive_field and the chunk_size, so if you want to use the wieghts of CALF_benchmark, you should not change any of these parameters. 

On the first hand, for the first error, could you please either share with me your feature file or tell me what size you get when you load it with numpy and try to get its shape ? 

<code>
import numpy as np \
features = np.load("bd4_out_features.npy") \
print(features.shape)
</code>

Thanks in advance,

**Comment by yurii-pryimak** [comment]
```
`import numpy as np
features = np.load("../bd4/bd4_out_features.npy")
print(f'Output_features_shape:{features.shape}')`
```

Output_features_shape:(20, 512)

**Comment by cioppaanthony** [comment]
Oh ok, this is a very short clip. How long was your original video file before extracting the features ? From the shape I would say 20/2 = 10 seconds right ?

Our method is designed to treat entire half times of games (+-45 minutes). Your video should at least be greater than 2 minutes, corresponding to the chunk_size.

**Comment by yurii-pryimak** [comment]
No, actually it's 13 minutes video.
`import cv2
cap = cv2.VideoCapture('./bd4/bd4.mp4')

frames_qty = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

duration = frames_qty/fps

print(f'Duration is {duration} seconds')
print(f'FPS: {fps}')
print(f'Resolution: {width}x{height}')

Duration is 833.2 seconds
FPS: 60.0
Resolution: 1920x1080

**Comment by cioppaanthony** [comment]
Alright, then something went from in the feature extraction. 
I will tag @SilvioGiancola that may help with that.

**Comment by yurii-pryimak** [comment]
Sorry, my fault. Accidentally I limit duration to 10 seconds while Features Extraction

!python ./Features/VideoFeatureExtractor.py --path_video ../bd4/bd4.mp4 --path_features ../bd4/bd4_out_features.npy --overwrite --PCA "Features/pca_512_TF2.pkl" --PCA_scaler "Features/average_512_TF2.pkl" --start 1 --duration 10

I'll rerun it and let you to know about results

**Comment by yurii-pryimak** [comment]
After I extract features for full duration:
`import numpy as np
features = np.load("../bd4/bd4_out_features.npy")
print(f'Output_features_shape:{features.shape}')`

Output_features_shape:(1666, 512)

`!python src/main.py --SoccerNet_path=../../../ \
--features=bd4_out_features.npy \
--num_features=512 \
--model_name=CALF_benchmark \
--test_only`

`Traceback (most recent call last):
  File "src/main.py", line 164, in <module>
    main(args)
  File "src/main.py", line 83, in main
    a_mAP, a_mAP_per_class, a_mAP_visible, a_mAP_per_class_visible, a_mAP_unshown, a_mAP_per_class_unshown = test(test_loader, model=model, model_name=args.model_name, save_predictions=True)
  File "/content/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/train.py", line 264, in test
    predictions2json(detections_numpy[index*2], detections_numpy[(index*2)+1],"outputs/", list_game[index], model.framerate)
IndexError: list index out of range`

**Comment by cioppaanthony** [comment]
Try replacing line 262 of train.py:
list_game = getListGames(dataloader.dataset.split) ->list_game = ['bd4/']

**Comment by yurii-pryimak** [comment]
@cioppaanthony Thank you! It's working now,

**Comment by cioppaanthony** [comment]
Awesome @yurii-pryimak! Glad it worked!

**Comment by Al-Hussein-96** [comment]
@cioppaanthony  thanks for your response, working

**Comment by cioppaanthony** [comment]
As promised, here is the inference pipeline on external videos:

https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF/inference

Don't hesitate to tell me if it does not work properly, or simply what could be improved.

Enjoy.
