### ISSUE TITLE
Is there direct download link for feature embeddings?

### ISSUE THREAD

**Issue by rtxbae** [SilvioGiancola/SoccerNetv2-DevKit#52]
Hey, I noticed that once agreed to the NDA for the videos, we could download them via a hosting cloud. I wonder do we have this for the embeddings? I have a connection issue where downloading it using the soccernet tool I got intermittent failure multiple times, and it's at reduced speed for some reason (not sure if this is by design).

Thanks!

**Comment by SilvioGiancola** [comment]
Hey, their is no throttle when downloading data, it should use the full bandwidth. Do you still have slow downloads?
