### ISSUE TITLE
Using a different version of libraries

### ISSUE THREAD

**Issue by AadityaBodke** [SilvioGiancola/SoccerNetv2-DevKit#56]
### Running `pip3 install torch==1.6.0 torchvision==0.7.0 -f https://download.pytorch.org/whl/cu101/torch_stable.html`
Gives.................

> Looking in links: https://download.pytorch.org/whl/cu101/torch_stable.html
> ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
> ERROR: No matching distribution found for torch==1.6.0

### Running `conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch`
Gives....................

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - cudatoolkit=10.1
>   - pytorch==1.6.0
>   - torchvision==0.7.0
> 
> Current channels:
> 
>   - https://conda.anaconda.org/pytorch/linux-aarch64
>   - https://conda.anaconda.org/pytorch/noarch
>   - https://conda.anaconda.org/conda-forge/linux-aarch64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/linux-aarch64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-aarch64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

### Since I cannot install the required versions, will installing higher versions break the code?
Thanks for your amazing work.

**Comment by SilvioGiancola** [comment]
It should not, but I cannot possibly try all versions. I would also recommend checking the updated repository on action spotting here: https://github.com/SoccerNet/sn-spotting
