### ISSUE TITLE
Inference code of TemporallyAware model on custom mp4 files

### ISSUE THREAD

**Issue by mkoursha** [SilvioGiancola/SoccerNetv2-DevKit#59]
Thanks for great work and making it public.

How can i use pre-trained model of TemporallyAware on my custom .mp4 files like the one in CALF model.

Can you provide any inference script for that.

Best regards.

Mahdi Khoursha.

**Comment by SilvioGiancola** [comment]
Hi @mkoursha, 

This code does not have an inference function with NetVLAD++. It shouldn't be too complicated to adapt it; if you find a way, feel free to do a pull request. For Action Spotting, we are building a stronger library, more flexible, on https://github.com/OpenSportsLab/OSL-ActionSpotting. We do have an inference function for NetVLAD++ in that library.

Best,

**Comment by mkoursha** [comment]
Thanks for your response

I've added a inference procedure on .mp4 files but the performance is poor.

What should i do?

**Comment by SilvioGiancola** [comment]
You can try newer models from https://github.com/OpenSportsLab/OSL-ActionSpotting.

**Comment by SilvioGiancola** [comment]
PS: Feel free to do a PR to share your inference code.
