### ISSUE TITLE
homography params at calibration_ccbv.json

### ISSUE THREAD

**Issue by ofirliba** [SilvioGiancola/SoccerNetv2-DevKit#6]
how can I use those Homography params to transform a current frame into a top view?

for Example , If I use opencv function, what is H ? ( do I need to normalize the json's params ? inverse?)
what is output dimensions of this transform?

warp = cv2.warpPerspective(currFrame, H, (outWidth, outHeight))

**Comment by SilvioGiancola** [comment]
Hi @ofirliba,

You can [open the json](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/deda7eaae95de2637d43730a7708fc8199245ad9/Task1-ActionSpotting/Calibration_GCN/src/dataset.py#L160), then [read the homography](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/deda7eaae95de2637d43730a7708fc8199245ad9/Task1-ActionSpotting/Calibration_GCN/src/dataset.py#L180) and [apply the homography](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/deda7eaae95de2637d43730a7708fc8199245ad9/Task1-ActionSpotting/Calibration_GCN/src/dataset.py#L190) using the [build-in unproject_image_point function](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/deda7eaae95de2637d43730a7708fc8199245ad9/Task1-ActionSpotting/Calibration_GCN/src/preprocessing.py#L5).

We have not used the [cv2.warpPerspective](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#gaf73673a7e8e18ec6963e3774e6a94b87) function.

Best

**Comment by LittleFanFan** [comment]
Before doing cv2.warpPerspective, you may need to do the translation and scaling to project the original frame. I mean, use matrix multiplication on H.
