### ISSUE TITLE
trying to reduce dataset to train but exception occurs 

### ISSUE THREAD

**Issue by Al-Hussein-96** [SilvioGiancola/SoccerNetv2-DevKit#9]
I download SoccerNet locally then remove multiple games from files (SoccerNetGamesTrain.json,SoccerNetGamesValid.json,SoccerNetGamesTest.json)

but the following exception occurs:
`2021-06-26 12:46:56,913 [MainThread  ] [INFO ]  Total number of parameters: 578245
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
2021-06-26 12:46:56,915 [MainThread  ] [INFO ]  start training
  0%|                                                                                                                                   | 0/563 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Train 1: Time 0.040s (it:0.030s) Data:0.001s (it:0.000s) Loss 1.4038e+02 Loss Seg 2.6572e+04 Loss Spot 1.3063e+02 : 100%|█████| 563/563 [00:22<00:00, 25.23it/s]
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
  0%|                                                                                                                                   | 0/563 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 164, in <module>
    main(args)
  File "src/main.py", line 77, in main
    max_epochs=args.max_epochs, evaluation_frequency=args.evaluation_frequency)
  File "/content/drive/My Drive/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/train.py", line 53, in trainer
    train = False)
  File "/content/drive/My Drive/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/train.py", line 138, in train
    for i, (feats, labels, targets) in t: 
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/SoccerNetv2-DevKit/Task1-ActionSpotting/CALF/src/dataset.py", line 127, in __getitem__
    event_selection = random.randint(0, len(self.game_anchors[class_selection])-1)
  File "/usr/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)`

**Comment by SilvioGiancola** [comment]
You have an issue in line 127 of `Task1-ActionSpotting/CALF/src/dataset.py`, in the function `__getitem__`. `__getitem__` randomly selects the clips to train on and apparently it fails at selecting a random clip.

I am not sure how we can help you with that, especially with such limited of amount of information you are providing about your issue. From the previous issue, I recon you have done critical changes to the code and the data, you now have a completely different setup it was not originally designed for.

**Comment by Al-Hussein-96** [comment]
> You have an issue in line 127 of `Task1-ActionSpotting/CALF/src/dataset.py`, in the function `__getitem__`. `__getitem__` randomly selects the clips to train on and apparently it fails at selecting a random clip.
> 
> I am not sure how we can help you with that, especially with such limited of amount of information you are providing about your issue. From the previous issue, I recon you have done critical changes to the code and the data, you now have a completely different setup it was not originally designed for.

No I didn't make big changes I just reduced the number of matches (datasets) to try to understand the training process
I just deleted a number of matches from a file (SoccerNetGamesTrain.json,SoccerNetGamesValid.json,SoccerNetGamesTest.json) 

like this: 
`{
    "england_epl": {
        "2014-2015": [
            "2015-02-21 - 18-00 Chelsea 1 - 1 Burnley",
            "2015-02-21 - 18-00 Crystal Palace 1 - 2 Arsenal",
            "2015-02-21 - 18-00 Swansea 2 - 1 Manchester United",
            "2015-02-22 - 19-15 Southampton 0 - 2 Liverpool"
        ],
        "2015-2016": [

        ],
        "2016-2017": [

        ]
    },
    "europe_uefa-champions-league": {
        "2014-2015": [
       
        ],
        "2015-2016": [
           
        ],
        "2016-2017": [
          
        ]
    },
    "france_ligue-1": {
        "2014-2015": [
        ],
        "2015-2016": [
          
        ],
        "2016-2017": [
          
        ]
    },
    "germany_bundesliga": {
        "2014-2015": [
          
        ],
        "2015-2016": [
          
        ],
        "2016-2017": [
          
        ]
    },
    "italy_serie-a": {
        "2014-2015": [
         
        ],
        "2015-2016": [
         
        ],
        "2016-2017": [
         
        ]
    },
    "spain_laliga": {
        "2014-2015": [
          
        ],
        "2015-2016": [
         
        ],
        "2016-2017": [
        
        ]
    }
}`

**Comment by SilvioGiancola** [comment]
The code is expecting to have at least 1 instance of each class. If you remove some game and for some reason a class has no instance (e.g. red card) then that code won't be able to sample a clip with a red card. That might be your issue.

**Comment by Al-Hussein-96** [comment]
> The code is expecting to have at least 1 instance of each class. If you remove some game and for some reason a class has no instance (e.g. red card) then that code won't be able to sample a clip with a red card. That might be your issue.

Wow, ok thanks you very much
